"""
Script to create the v9.docx template file.
Run this once to generate the template used by the main application.
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT


def create_template():
    doc = Document()

    # Set page margins (narrow margins for more image space)
    for section in doc.sections:
        section.top_margin = Cm(1.27)
        section.bottom_margin = Cm(1.27)
        section.left_margin = Cm(1.27)
        section.right_margin = Cm(1.27)
        section.page_width = Inches(8.5)
        section.page_height = Inches(11)

    # Add a placeholder paragraph (will be cleared by the app)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Template Document - Generated by Document Creator App")
    run.font.name = "Times New Roman"
    run.font.size = Pt(14)

    doc.save("v9.docx")
    print("Template v9.docx created successfully!")


if __name__ == "__main__":
    create_template()
