# Modeling and Forecasting the Morocco Stock Index 20

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
# Loading libraries
# Date manipulation
suppressPackageStartupMessages(library(lubridate))

# Descriptive statistics  
suppressPackageStartupMessages(library(fBasics))

# Coefficient significance tests
suppressPackageStartupMessages(library(lmtest))

# Unit root test
suppressPackageStartupMessages(library(urca))

# Visualisation
suppressPackageStartupMessages(library(ggplot2))

# Return calculations
suppressPackageStartupMessages(library(quantmod))
suppressPackageStartupMessages(library(PerformanceAnalytics))
suppressPackageStartupMessages(library(forecast))

# Changements structurels
suppressPackageStartupMessages(library(strucchange))

# Loading the 'tseries' library for ADF testing 
library(tseries)
library(timeSeries) 
library(xts) 
library(pastecs)
# For MLP model
library(nnfor)
```

```{r }
library(readr)
dailyMSI20 <- read.csv("MSI20_update.csv", head = TRUE)
head(dailyMSI20)
```

```{r }
# Clean data
# Convert Date column to time format
dailyMSI20$Date <- as.Date(dailyMSI20$Date)

# Check updated format
str(dailyMSI20)

```

```{r }

head(dailyMSI20)

```

```{r }
tail(dailyMSI20)
```

```{r }
dim(dailyMSI20)
```

```{r }
#count the total number of missing values in the dataset
sum(is.na(dailyMSI20))

```

```{r }
t(stat.desc(dailyMSI20))

```

```{r }
#Prices in time series format
Close_Price <- xts(dailyMSI20[,3],order.by=as.Date(dailyMSI20[,1]))
head(Close_Price)
```

```{r }
tail(Close_Price)

```

```{r }

autoplot(Close_Price) +
  labs(title = "MSI 20 daily closing price",
       x = "Date: January 4, 2021 to May 5, 2023",
       y = "Closing price")
```

Here we see the corresponding chart, as produced by chartSeries in the quantmod package.

```{r }
chart_Series(Close_Price, name = deparse(substitute(Daily_closing_price_of_MSI_20)),col = "blue")

```

```{r }
# Plot ACF
acf(Close_Price, main = "MSI 20 autocorrelation function (ACF)", col = "blue",
    lag.max = 100)
```

```{r }
# Plot PACF
pacf(Close_Price, main = "MSI 20 partial autocorrelation function (PACF)",
     col = "blue",lag.max = 100)
```

```{r }
#Perform ADF test
adf_test <- adf.test(Close_Price)

#Print test results
print(adf_test)

```

```{r }
returns_MSI20 <- diff(log(Close_Price))[-1,]
head(returns_MSI20)

```

```{r }

autoplot(returns_MSI20) +
  labs(x = "Years",
       y = "Return",
       title = "MSI 20 closing price returns")
```

```{r }
plot(returns_MSI20)
```

```{r }
library(gridExtra)
ACF_plot <- ggAcf(returns_MSI20, main="ACF of MSI 20 returns",lag=50, ylim=c(-0.3,0.3))+
  theme(plot.title = element_text(size = 12))

PACF_plot <- ggPacf(returns_MSI20, main= "PACF returns MSI 20", lag=50,ylim=c(-0.3,0.3))+
  theme(plot.title = element_text(size = 12))

grid.arrange(ACF_plot, PACF_plot, nrow = 1)
```

```{r }
ACF_plot <- acf(returns_MSI20, main="ACF of MSI 20 returns",lag=10, ylim=c(-0.3,0.3))+
  theme(plot.title = element_text(size = 12),las=1)
```

```{r }
PACF_plot <- pacf(returns_MSI20, main= "PACF returns MSI 20", lag=10,ylim=c(-0.3,0.3))+
  theme(plot.title = element_text(size = 12))
```

```{r }
pacf(returns_MSI20, main= "PACF returns MSI 20", lag=10,ylim=c(-0.3,0.3))+
  theme(plot.title = element_text(size = 12))
```

```{r }
# Phillips-Perron (PP) test
pp_test <- pp.test(returns_MSI20)
print(pp_test)
```

```{r }
#  Kwiatkowski-Phillips-Schmidt-Shin-Test (KPSS)
kpss_test <- kpss.test(returns_MSI20)
print(kpss_test)
```

```{r }
# Augmented Dickey-Fuller (ADF) test
Adf_test <- adf.test(returns_MSI20)
print(Adf_test)
```

```{r }
#  Augmented Dickey-Fuller (ADF) tests
adf_test <- ur.df(returns_MSI20)
summary(adf_test)
```

```{r }
# splitting into train and test data
train_MSI20 <- Close_Price[1:531] # 2021-01-04 --> 2023-02-09 (531 Obs.) 
test_MSI20 <- Close_Price[532:590] # 2023-02-10 -->2023-05-05 (59 Obs.)
```

```{r }
model1 <- arima(train_MSI20, order=c(1,1,1),method="CSS")
library(lmtest)
coeftest(model1)
```

```{r }
calculate_bic <- function(arima_model, data) {
  # Calculate the number of parameters in the model
  k <- length(coef(arima_model))
  
  # Calculate BIC
  bic <- -2 * logLik(arima_model) + k * log(length(data))
  
  return(bic)
}
```

```{r }
model1 <- arima(train_MSI20, order=c(1,1,1),method="ML")
coeftest(model1)
```

```{r }
summary(model1)

```

```{r }
bic_model1 <- calculate_bic(model1, train_MSI20)
print(bic_model1)
```

```{r }
library(knitr)
opts_knit$set(global.par = TRUE)
```

```{r }
par(mar=c(5,5,0,0)) #it's important to have this in a separate piece
autoplot(model1)
```

```{r }
model2 <- arima(train_MSI20, order=c(2,1,2),method="ML")
coeftest(model2)
```

```{r }
summary(model2)
```

```{r }
bic_model2 <- calculate_bic(model2, train_MSI20)
print(bic_model2)
```

```{r }
par(mar=c(5,5,0,0)) 
autoplot(model2)
```

```{r }
model3 <- arima(train_MSI20, order=c(2,1,0),method="ML")
coeftest(model3)
```

```{r }
summary(model3)
```

```{r }
bic_model3 <- calculate_bic(model3, train_MSI20)
print(bic_model3)
```

```{r }
par(mar=c(5,5,0,0)) 
autoplot(model3)
```

```{r }
model4 <- arima(train_MSI20, order=c(0,1,2),method="ML")
coeftest(model4)
```

```{r }
summary(model4)
```

```{r }
bic_model4 <- calculate_bic(model4, train_MSI20)
print(bic_model4)
```

```{r }
par(mar=c(5,5,0,0)) 
autoplot(model4)
```

```{r }
checkresiduals(model4)
```

```{r }
resi.ima <- residuals(model4)
tsoutliers(resi.ima)
```

```{r }
resid_ts_clean_ima = tsclean(resi.ima)
```

```{r }
#resid_ts_clean_ima_tra = sqrt(resid_ts_clean_ima)
resid_ts_clean_ima_tra = (resid_ts_clean_ima)^(1/3)
```

```{r }
# Assuming resid_ts_clean_ima_tra is a time series object

# Impute missing values using linear interpolation
resid_imputed <- na.approx(resid_ts_clean_ima_tra)
```

```{r }
# diagnostic of the series for cleaned residues
checkresiduals(resid_imputed)
```

```{r }
hist(resid_imputed, prob=TRUE, 24,main = paste("Histogram of residuals ARIMA(0,1,2) model" ),
     xlab ="Residuals",lwd=2)   # histogram 
# Grid below plot
# Vertical grid
abline(v = seq(-0.02, 0.02, 0.0025),
       lty = 2, col = "gray")

# Horizontal grid  
abline(h = seq(0, 80, 10),
       lty = 2, col = "gray")
lines(density(resid_imputed),type="l", col="blue", lwd=2)     # smooth it - ?density for details 
```

```{r }
library(ggpubr)
ggqqplot(resid_imputed,title = "Q-Q plot of residuals from ARIMA(0,1,2) model", merge = FALSE) 
```

```{r }
tsdisplay(resid_imputed, lag.max=100, main="ARIMA(0,1,2) Model Residuals")
```

```{r }
#Tests auto-correlation of order greater than 1
Box.test(resid_imputed, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)
```

```{r }
# Test of normality
# Perform the Jarque-Bera test on the imputed time series
result_test_jb <- jarque.bera.test(resid_imputed)
print(result_test_jb)
```

```{r }
# Perform the Shapiro-Wilk test
resultat_test_sh <- shapiro.test(resid_imputed)

# Show test results
print(resultat_test_sh)
```

```{r }
# Load package
library(nortest)
forecast_test <- Arima(test_MSI20,model=model4)$fitted
autoplot(ts(test_MSI20), series = 'test',xlab ="Date",ylab="Closing prices transformed") +
autolayer(forecast_test, series = 'ARIMA(0,1,2)',PI =FALSE) +
ggtitle("MSI 20 closing prices prediction")+
scale_colour_manual(values = c('test'='black', 'ARIMA(0,1,2)'='red'),

breaks = c('test', 'ARIMA(0,1,2)'))
```

```{r }
## Create a time series object
## create the zoo object as before
forecast_ts <- zoo(forecast_test , dailyMSI20[532:590,1]) ### 2023-02-10 
#to 2023-05-05 (59 Obs.)

head(forecast_ts)
```

```{r }
tail(forecast_ts)
```

```{r }
forecast_ts <- ts(forecast_test,  
           start = c(2023, as.numeric(format(dailyMSI20[532:590,1], "%j"))))
head(forecast_ts)
```

```{r }
# merge into multivariate time series
ts.merge <- merge(test_MSI20, as.zoo(forecast_ts))

colnames(ts.merge) <- c("ts_test", "ts_forecast")
#as.ts(ts.merge)
head(ts.merge)
```

```{r }
tail(ts.merge)

```

```{r }
forecast_model4 <- forecast(model4, h = 59)
accuracy(forecast_model4,test_MSI20)
```
